[package]
name = "lacombiner"
version = "0.1.0"
authors = ["piedoom <alexanderpaullozada@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.2"
clap = "*"
colored = "1.7"
glob = "0.3.0"
image = "*"